feat: 0001 user model api
likelion-kookmin/msof_api pull request #13
Opened 2021-03-23 15:40 UTC by rkdtmddnjs97

2021-03-23 15:56 UTC, shinkeonkim requested changes
고생하셨습니다. 👍

2021-03-23 15:56 UTC, shinkeonkim commented on accounts/admin.py
> +"""
`p3` module docstring 자세히 써주세요

2021-03-23 15:56 UTC, shinkeonkim commented on accounts/admin.py
> +# Register your models here.
`p1` 주석은 지워주세요

2021-03-23 15:56 UTC, shinkeonkim commented on accounts/admin.py
> +admin.site.register(Univerisity)
`p2` UserAdmin, UniversityAdmin 클래스도 만들어주시면, 나중에 더 편할 듯 합니다.

2021-03-23 15:56 UTC, shinkeonkim commented on accounts/apps.py
> +"""
`p3` 요기도 module docstring 자세히 남겨주시면 좋을 것 같습니다.

2021-03-23 15:56 UTC, shinkeonkim commented on accounts/apps.py
> +    """appconfig를 상속받고요"""
`p3` 클래스 독스트링도 자세히 써주시면 좋을 것 같습니다.

2021-03-23 15:56 UTC, shinkeonkim commented on accounts/models.py
> +"""
`p3` module docstring을 자세히 써주세욥

2021-03-23 15:56 UTC, shinkeonkim commented on accounts/models.py
> +    total_point = models.PositiveIntegerField(default=0)
`p2` 필드마다 verbose_name 옵션을 추가해주세요. 어드민 상에서 데이터를 보았을 때, 가독성있게 바꾸어주세요.
지금은 어드민 상에서 영어로 보일거에요.

2021-03-23 15:56 UTC, shinkeonkim commented on msof_api/config/common.py
> +from os.path import join
`p3` import os , import os.path 로 두번 가져오고 있는데
join을 쓰는 곳이 많지 않다면 그냥 os.path.join으로 해도 괜찮을 것 같아요.
혹은 가져오는 모듈들을 정확히 명시에서 import 하거나요

2021-03-23 15:56 UTC, shinkeonkim commented on accounts/serializers.py
> +User serailizer입니다. password가 보이니까 field 관련 부분 수정해야됩니당
`p1` `FIXME: 블라블라` 로 명시적으로 적어주세요.
혹은 바로 이 이슈를 해결하는 게 좋을 것 같네요. 비밀번호가 보이는 건 너무 크리티컬한 이슈인 것 같습니다.

2021-03-23 15:56 UTC, shinkeonkim commented on accounts/models.py
> +    total_point = models.PositiveIntegerField(default=0)
`p3` 포인트가 - 일리는 없겠죠..?

2021-03-23 15:56 UTC, shinkeonkim commented on requirements.txt
> +wcwidth==0.2.5
`p3` 조금 고민되네요. 구분지어 놓긴 했는데, 이렇게 점점 많아지면 구분 일일이 하기도 힘든데...그냥 둘까요?

2021-03-23 16:09 UTC, Aqudi commented on accounts/admin.py
> +"""
한 줄 DocString """DocString"""

여러줄
"""제목

내용"""

2021-03-23 16:12 UTC, Aqudi commented on accounts/apps.py
> +"""
**한 줄**
 """Do X and return a list."""

**여러줄**
"""Form a complex number.

Keyword arguments:
real -- the real part (default 0.0)
imag -- the imaginary part (default 0.0)
"""

2021-03-23 16:15 UTC, Aqudi commented on accounts/models.py
> +    total_point = models.PositiveIntegerField(default=0)
#14 지켜주세요

2021-03-23 16:15 UTC, Aqudi commented on accounts/serializers.py
> +User serailizer입니다. password가 보이니까 field 관련 부분 수정해야됩니당
#14 지켜주세요

2021-03-23 16:19 UTC, Aqudi commented on accounts/models.py
> +"""
#14 지켜주세요

2021-03-23 16:19 UTC, Aqudi commented on accounts/models.py
> +    name = models.CharField(max_length=100)
#14 지켜주세요

2021-03-23 16:19 UTC, Aqudi commented on accounts/serializers.py
> +"""
#14 지켜주세요

2021-03-23 16:19 UTC, Aqudi commented on accounts/serializers.py
> +    """
이거는 왜 설명이 meta class 인가요?

2021-03-23 16:19 UTC, Aqudi commented on accounts/urls.py
> +"""
#14 지켜주세요

2021-03-23 16:19 UTC, Aqudi commented on accounts/views.py
> +"""
#14 지켜주세요

2021-03-24 07:35 UTC, rkdtmddnjs97 commented on accounts/serializers.py
> +    """
ㅋㅋㅋㅋㅋㅋㅋ급하게 쓰느라

2021-03-24 07:35 UTC, rkdtmddnjs97 commented on accounts/views.py
> +"""
알았어요 죄송해요

2021-03-26 18:38 UTC, dadahee commented on requirements.txt
> +wcwidth==0.2.5
더 커지기 전에 호로록 구분 해놓는 편이 좋을 거 같아요...!

2021-03-26 18:38 UTC, dadahee commented on accounts/models.py
> +    total_point = models.PositiveIntegerField(default=0)
university의 null, blank 옵션이 true일 필요가 있나요?

2021-03-26 18:41 UTC, dadahee reviewed
고생하셨습니다 😔😔

2021-03-26 18:50 UTC, dadahee reviewed
고생하셨습니다 !!

2021-03-26 18:50 UTC, dadahee commented on accounts/models.py
> +    univerisity = models.ForeignKey(Univerisity, on_delete=models.CASCADE, null=True, blank=True)
university의 null, blank 옵션이 true일 필요가 있나요?

2021-03-26 18:50 UTC, dadahee commented on msof_api/urls.py
>      # http://www.django-rest-framework.org/api-guide/routers/#defaultrouter
정말 궁금해서 여쭤보는 건데 이 주석은 보통 냅두나요?

2021-03-27 12:33 UTC, shinkeonkim commented on msof_api/urls.py
>      # http://www.django-rest-framework.org/api-guide/routers/#defaultrouter
지우는게 좋을 것 같네요

2021-03-27 12:34 UTC, shinkeonkim commented on accounts/models.py
> +    univerisity = models.ForeignKey(Univerisity, on_delete=models.CASCADE, null=True, blank=True)
admin user나 특정 유저는 대학 정보가 없을 수도 있지 않을까요?

2021-03-27 15:05 UTC, kkIIun commented on accounts/models.py
> +    univerisity = models.ForeignKey(Univerisity, on_delete=models.CASCADE, null=True, blank=True)
max_length가 너무 값이 큰 것 같습니다!

2021-03-27 15:05 UTC, kkIIun commented on accounts/models.py
> +    name = models.CharField(max_length=100)
max_length가 너무 값이 큰 것 같습니다!

2021-03-29 00:15 UTC, rkdtmddnjs97 commented on msof_api/config/common.py
> +from os.path import join
??? 저거 제가 추가한거 아닌데요?
뭐지

2021-03-30 16:38 UTC, dadahee approved these changes

2021-04-03 05:50 UTC, kkIIun approved these changes

2021-04-04 06:44 UTC, shinkeonkim approved these changes

2021-04-04 06:44 UTC, shinkeonkim commented on accounts/admin.py
> +admin.site.register(Univerisity)
아래쪽에 있으면 굳이 중복으로 안 넣으셔도 됩니다. 날려주세욥

2021-04-04 06:44 UTC, shinkeonkim commented on accounts/urls.py
> +"""account 앱으 url 라우터 등록"""
앱으 -> 앱의

2021-04-10 07:06 UTC, merged