Fix: 0050 activity signal
likelion-kookmin/msof_api pull request #53
Opened 2021-06-09 04:00 UTC by kkIIun

2021-06-11 12:57 UTC, shinkeonkim requested changes

2021-06-11 12:57 UTC, shinkeonkim commented on msof_api/activity/signals.py
> +def create_like_activity_and_reset_liked_count(sender, **kwargs):
음.. 함수명을 조금 바꿔야 하지 않을까요? 이제 like_activity를 만드는 부분은 없어보여요

2021-06-13 15:17 UTC, kkIIun commented on msof_api/activity/signals.py
> +def create_like_activity_and_reset_liked_count(sender, **kwargs):
85번줄에 create_like_activity_and_reset_user_total_point가 있어서 그런건데 바꿔야할까요?

2021-07-11 07:17 UTC, shinkeonkim commented on msof_api/activity/signals.py
> +def create_like_activity_and_reset_liked_count(sender, **kwargs):
like activity가 만들어지는게 API view에서 해야 하는거 아닌가요?
거기서 만들어지는 signal을 받아서 count를 갱신해야죠

2021-07-24 16:32 UTC, shinkeonkim commented on msof_api/activity/signals.py
> +def create_like_activity_and_reset_liked_count(sender, **kwargs):
현재 작업중인 내용과 상이해져서 해당 브랜치는 클로즈 하겠습니다.

2021-07-24 16:32 UTC, closed without merging