add: Activity Model
likelion-kookmin/msof_api pull request #8
Opened 2021-03-21 14:37 UTC by rlwjd4177

2021-03-21 14:50 UTC, Aqudi commented on requirements.txt
> -# Core
홀리 섹션을 나눠서 추가를 하도록 만들어둔 것 같은데..

2021-03-21 14:50 UTC, Aqudi commented on msof_api/log/admin.py
> +    readonly_fields = ["point"]
자동정렬 한 번 해주세요.
마지막에 new line이 있는게 좋습니다!

2021-03-21 14:52 UTC, Aqudi commented on msof_api/log/models.py
> +    ACTION_CHOICE = (
설계랑은 좀 다른 것 같습니다.
확인해주세요!

![image](https://user-images.githubusercontent.com/35187793/111909382-6d6a1000-8aa0-11eb-9596-6746933aa0ff.png)

2021-03-21 14:57 UTC, rlwjd4177 commented on msof_api/log/models.py
> +    ACTION_CHOICE = (
이 부분은 설계를 조금 다르게 해도 될 것 같아서 해보았는데 
다시 바꿔야할까요?

2021-03-21 14:58 UTC, rlwjd4177 commented on requirements.txt
> -# Core
아하..!

2021-03-23 01:48 UTC, Aqudi commented on msof_api/log/models.py
> +    ACTION_CHOICE = (
그럼 설계의 의미가..

2021-03-23 03:42 UTC, dadahee commented on msof_api/log/models.py
> +    ACTION_CHOICE = (
PointRule 모델 대신 ACTION_CHOICE로 choices 옵션을 주고, activity 속성을 추가한 건가요?
옵션이 추가되거나 수정할 때 save도 같이 수정해야 하니 설계대로 모델을 따로 두는 게 낫지 않을까 싶습니다...!

2021-03-23 04:56 UTC, rlwjd4177 commented on msof_api/log/models.py
> +    ACTION_CHOICE = (
수정했습니당

2021-03-23 04:57 UTC, rlwjd4177 commented on msof_api/log/admin.py
> +    readonly_fields = ["point"]
넴

2021-03-23 12:30 UTC, shinkeonkim requested changes

2021-03-23 12:30 UTC, shinkeonkim commented on msof_api/config/common.py
> +        'msof_api.log',
`p3` 뭔가 개인적으로는 log라는 앱의 이름은 아닌 것 같아요. 서버의 로그 기록을 저장하는 폴더이름 느낌이 너무 세게 드네요.
오히려 안에 모델이 Activity니까 activity 앱이라고 하는게 좋지 않을까 싶습니다.

2021-03-23 12:30 UTC, shinkeonkim commented on msof_api/log/views.py
> +# Create your views here.
형 pre-commit 설정되어 있는 것 맞나요?
이렇게 사용하지 않는 import 함수가 있으면 커밋이 안 될텐데 확인해주세요.

2021-03-23 12:30 UTC, shinkeonkim commented on msof_api/log/tests.py
> +# Create your tests here.
여기도 pre-commit에서 막았어야 하는 부분 같은데, 한번 pre-commit 확인해주세요.

2021-03-23 12:30 UTC, shinkeonkim commented on msof_api/log/models.py
> +    # TODO: str에 created를 추가해줘야함.
이슈만들어 주시고, 이슈 번호 반영해서, `#TODO: 0000 created_at을 __str__에 추가하기` 라는 식으로 주석추가해주세요.

2021-03-23 12:30 UTC, shinkeonkim commented on msof_api/log/models.py
> +        default=Action.ADD_QUESTION )
`p3` 그냥 name의  max_length 늘려서라도 가독성있게 튜플을 만들어주셔도 좋을 것 같습니다.

2021-03-23 12:30 UTC, shinkeonkim commented on msof_api/log/apps.py
> +    name = 'log'
app 네임 위에 적어놓은 거 한번 생각해주세욥..

2021-03-23 12:30 UTC, shinkeonkim commented on msof_api/log/models.py
> +    name = models.CharField(
`p1` verbose_name으로 컬럼명을 가독성있게 해주세요. 
아마 admin 페이지에서 영어로 나올거에요

2021-03-23 12:30 UTC, shinkeonkim commented on msof_api/log/models.py
> +    point_rule = models.ForeignKey(PointRule, on_delete = models.CASCADE)
`p1` 여기도 verbose_name 추가해주세요.

2021-03-23 12:30 UTC, shinkeonkim commented on msof_api/log/admin.py
> +    readonly_fields = ["point"]
`p3` ActivityAdmin에 point 필드 맞나요?
point 컬럼은 PointRule에 있는건데요? 어드민에서 확인해보셨나요?

2021-03-23 12:30 UTC, shinkeonkim commented on msof_api/log/models.py
> +# from msof_api.base_model import BaseModel
`p3` activity, poinRule 모델을 BaseModel 상속시키기 이슈 추가해주시고 TODO 주석 넣어주시면 좋을 것 같아요.

2021-03-23 15:51 UTC, rlwjd4177 commented on msof_api/config/common.py
> +        'msof_api.log',
수정했습니다

2021-03-23 15:51 UTC, rlwjd4177 commented on msof_api/log/views.py
> +# Create your views here.
수정했습니다

2021-03-23 15:51 UTC, rlwjd4177 commented on msof_api/log/tests.py
> +# Create your tests here.
수정했습니다

2021-03-23 15:51 UTC, rlwjd4177 commented on msof_api/log/models.py
> +    # TODO: str에 created를 추가해줘야함.
수정했습니다

2021-03-23 15:51 UTC, rlwjd4177 commented on msof_api/log/models.py
> +        default=Action.ADD_QUESTION )
수정했습니다

2021-03-23 15:51 UTC, rlwjd4177 commented on msof_api/log/apps.py
> +    name = 'log'
수정했습니다

2021-03-23 15:51 UTC, rlwjd4177 commented on msof_api/log/models.py
> +    name = models.CharField(
수정했습니다

2021-03-23 15:52 UTC, rlwjd4177 commented on msof_api/log/models.py
> +    point_rule = models.ForeignKey(PointRule, on_delete = models.CASCADE)
수정했습니다

2021-03-23 15:52 UTC, rlwjd4177 commented on msof_api/log/admin.py
> +    readonly_fields = ["point"]
수정했습니다

2021-03-23 15:52 UTC, rlwjd4177 commented on msof_api/log/models.py
> +# from msof_api.base_model import BaseModel
추가했습니다

2021-03-28 07:46 UTC, shinkeonkim approved these changes

2021-03-28 07:46 UTC, shinkeonkim commented on .vscode/settings.json
> +}
파일 맨끝에 라인 하나 추가해주시면 좋을 것 같습니다. 
(사실 .vscode/ 디렉토리는 굳이 안 올리셔도 괜찮습니다유)
참고: https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

2021-03-29 15:08 UTC, dadahee approved these changes
고생 많으셨습니다 😲😁

2021-03-29 15:08 UTC, dadahee commented on msof_api/activity/models.py
> +    )
오! 구조가 깔끔하고 멋집니다 👍👍👍

2021-03-31 12:05 UTC, merged