feat: 0002 Question and Comment model
likelion-kookmin/msof_api pull request #9
Opened 2021-03-23 03:31 UTC by dadahee

- `pylint` 제대로 쓰는 건 처음이라 혹시 docstring 등 부족한 거 있음 말해주세요!!
- `common.py` 자꾸 모듈 없다고 떠서 빼고 푸시했어요...

2021-03-23 03:45 UTC, Aqudi commented on msof_api/question/admin.py
> +    '''
+ `"""한 줄 DocString"""`
+ 여러줄 Docstring
  ```
  """제목
  
  내용"""
  ```

2021-03-23 03:45 UTC, Aqudi commented on msof_api/question/models.py
> +# from msof_api.users.models import User
", '을 하나로 통일하는게 좋지 않을까.. 싶습니다.

2021-03-23 12:31 UTC, shinkeonkim commented on msof_api/question/models.py
> +# from msof_api.users.models import User
"가 좋을 듯 합니다.

2021-03-23 12:44 UTC, shinkeonkim requested changes

2021-03-23 12:44 UTC, shinkeonkim commented on msof_api/question/models.py
> +
`p1` verbose_name을 추가해서 컬럼명을 가독성있게 바꾸어주세요.
admint상에서 확인하시면 아마 영어로 보일겁니다.

2021-03-23 12:44 UTC, shinkeonkim commented on msof_api/question/models.py
> +        self.save()
`p3` 여기서 count가 동사가 아닌 명사의 느낌이고,
메서드는 동사로 시작하는게 좋을 것 같아요. increase? decrease? 라는 식으로든, 동사가 먼저 앞으로 나오는게 더 좋을 것 같아요.
increase_count? 정도로요.

2021-03-23 12:44 UTC, shinkeonkim commented on msof_api/question/models.py
> +    status = models.IntegerField(default=0)
`p3` 뭔가 status의 의미가 불분명해지는 것 같아요. 
이름을 바꿔보는건 어떨까요..?
왜 status에 +1이 되는거죠..?

2021-03-23 12:44 UTC, shinkeonkim commented on msof_api/question/models.py
> +        self.save()
`p3` 여기도 위와 같습니다.

2021-03-23 12:44 UTC, shinkeonkim commented on msof_api/question/models.py
> +        return f"{self.question}에 답변한 글"
`p3` 이슈로 Question, Comment모델에 author 관련 작업하기 라고 등록해주시고,
`# TODO: {이슈번호} Question, Comment모델에 author 관련 작업하기` 라는 식으로 주석추가해주세요.

2021-03-23 12:44 UTC, shinkeonkim commented on msof_api/question/models.py
> +    # 구조에 없었는데 필요해 보여서 일단 넣음
`p3` 뭘 넣으셨다는 걸까요?

2021-03-23 12:44 UTC, shinkeonkim commented on msof_api/question/models.py
> +        self.save()
`p3` reject도 필요한가요..?

2021-03-23 12:44 UTC, shinkeonkim commented on msof_api/question/models.py
> +MAX_TITLE_LENGTH = 200
`p3` MAX_TITLE_LENGTH을 class constant로 넣어주시는게 어떨까요?

2021-03-23 12:44 UTC, shinkeonkim commented on msof_api/question/models.py
> +    status = models.IntegerField(default=0)
`p1` 여기도 verbose_name 추가해주시면 좋을 것 같습니다.

2021-03-23 12:44 UTC, shinkeonkim commented on msof_api/question/models.py
> +"""
`p1` 이건 여기에 적을 건 아닌데, 마땅히 적을 곳이 없어서
여기에 남깁니다. commons.py에 INSTALLED_APP에 msof_api.question 앱을 추가해주셔야합니다.
아마 테스트도 안 되셨을 것 같은데 맞을까요?
어드민 사이트 상에서 데이터들 잘 만들어지는지 한번 확인부탁드립니다.

2021-03-24 08:16 UTC, dadahee commented on msof_api/question/models.py
> +    status = models.IntegerField(default=0)
@shinkeonkim status가 추천수 속성이라고 이해해서 +-1씩 증감하는 메소드만 구현했는데 잘못 이해한 걸까요?

2021-03-24 08:20 UTC, dadahee commented on msof_api/question/models.py
> +    # 구조에 없었는데 필요해 보여서 일단 넣음
@shinkeonkim 스키마에는 없지만 Comment 클래스도 `author`가 필요해보여서 일단 추가 해놨어요

2021-03-25 15:03 UTC, kkIIun approved these changes

2021-03-26 18:30 UTC, dadahee commented on msof_api/question/models.py
> +    )
스키마대로 status를 integerField로 설정하고 choices 옵션을 만들어 두었는데, 아무래도 알아보기 힘들 것 같아 고민이 됩니다 😂

2021-03-26 23:58 UTC, Aqudi commented on msof_api/question/models.py
> +    )
어떤 부분에서 알아보기 힘들 것 같나요?

2021-03-27 00:28 UTC, Aqudi approved these changes
LGMT

2021-03-27 00:28 UTC, Aqudi commented on msof_api/question/models.py
> +    status = models.IntegerField(
PositiveSmalnteger나 SmallInteger로 바꿔도 괜찮겠네요

2021-03-27 12:32 UTC, shinkeonkim commented on msof_api/question/models.py
> +    )
inter값인게 알아보기 힘든게 우려된다면, 그냥 integer가 아니라 CharField로 넣어도 될 것 같습니다..!

2021-03-27 12:32 UTC, shinkeonkim approved these changes

2021-03-29 01:56 UTC, rkdtmddnjs97 commented on msof_api/question/models.py
> +    )
CharField에 choices 추천드립니다

2021-04-01 12:53 UTC, shinkeonkim approved these changes

2021-04-03 06:45 UTC, Aqudi approved these changes
LGMT 수고했습니다

2021-04-03 13:10 UTC, merged